services:
    davidiq.mailinglist.listener:
        class: davidiq\mailinglist\event\listener
        arguments:
            - @config
            - %core.root_path%
            - %core.php_ext%
            - @dbal.conn
        tags:
            - { name: event.listener }
